<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KanjiQuizSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kanjiArray = [
            ['kanji' => '一', 'hiragana' => 'いち', 'meaning' => 'One'],
            ['kanji' => '二', 'hiragana' => 'に', 'meaning' => 'Two'],
            ['kanji' => '三', 'hiragana' => 'さん', 'meaning' => 'Three'],
            ['kanji' => '四', 'hiragana' => 'し/よん', 'meaning' => 'Four'],
            ['kanji' => '五', 'hiragana' => 'ご', 'meaning' => 'Five'],
            ['kanji' => '六', 'hiragana' => 'ろく', 'meaning' => 'Six'],
            ['kanji' => '七', 'hiragana' => 'しち/なな', 'meaning' => 'Seven'],
            ['kanji' => '八', 'hiragana' => 'はち', 'meaning' => 'Eight'],
            ['kanji' => '九', 'hiragana' => 'きゅう/く', 'meaning' => 'Nine'],
            ['kanji' => '十', 'hiragana' => 'じゅう', 'meaning' => 'Ten'],
            ['kanji' => '百', 'hiragana' => 'ひゃく', 'meaning' => 'Hundred'],
            ['kanji' => '千', 'hiragana' => 'せん', 'meaning' => 'Thousand'],
            ['kanji' => '万', 'hiragana' => 'まん', 'meaning' => 'Ten Thousand'],
            ['kanji' => '円', 'hiragana' => 'えん', 'meaning' => 'Yen'],
            ['kanji' => '時', 'hiragana' => 'じ', 'meaning' => 'Time'],
            ['kanji' => '分', 'hiragana' => 'ふん/ぷん', 'meaning' => 'Minute'],
            ['kanji' => '今', 'hiragana' => 'いま', 'meaning' => 'Now'],
            ['kanji' => '何', 'hiragana' => 'なに/なん', 'meaning' => 'What'],
            ['kanji' => '日', 'hiragana' => 'にち/じつ', 'meaning' => 'Day'],
            ['kanji' => '月', 'hiragana' => 'げつ/つき', 'meaning' => 'Month/Moon'],
            ['kanji' => '火', 'hiragana' => 'か', 'meaning' => 'Fire'],
            ['kanji' => '水', 'hiragana' => 'すい/みず', 'meaning' => 'Water'],
            ['kanji' => '木', 'hiragana' => 'もく/き', 'meaning' => 'Tree'],
            ['kanji' => '金', 'hiragana' => 'きん', 'meaning' => 'Gold/Metal'],
            ['kanji' => '土', 'hiragana' => 'ど/つち', 'meaning' => 'Soil'],
            ['kanji' => '本', 'hiragana' => 'ほん', 'meaning' => 'Book'],
            ['kanji' => '人', 'hiragana' => 'ひと', 'meaning' => 'Person'],
            ['kanji' => '名', 'hiragana' => 'な', 'meaning' => 'Name'],
            ['kanji' => '子', 'hiragana' => 'こ', 'meaning' => 'Child'],
            ['kanji' => '女', 'hiragana' => 'おんな/じょ', 'meaning' => 'Woman'],
            ['kanji' => '男', 'hiragana' => 'おとこ/だん', 'meaning' => 'Man'],
            ['kanji' => '学', 'hiragana' => 'がく', 'meaning' => 'Study'],
            ['kanji' => '校', 'hiragana' => 'こう', 'meaning' => 'School'],
            ['kanji' => '先', 'hiragana' => 'さき', 'meaning' => 'Previous'],
            ['kanji' => '生', 'hiragana' => 'せい/しょう', 'meaning' => 'Life'],
            ['kanji' => '先生', 'hiragana' => 'せんせい', 'meaning' => 'Teacher'],
            ['kanji' => '何', 'hiragana' => 'なに/なん', 'meaning' => 'What'],
            ['kanji' => '十', 'hiragana' => 'じゅう', 'meaning' => 'Ten'],
            ['kanji' => '百', 'hiragana' => 'ひゃく', 'meaning' => 'Hundred'],
            ['kanji' => '千', 'hiragana' => 'せん', 'meaning' => 'Thousand'],
            ['kanji' => '万', 'hiragana' => 'まん', 'meaning' => 'Ten Thousand'],
            ['kanji' => '円', 'hiragana' => 'えん', 'meaning' => 'Yen'],
            ['kanji' => '時', 'hiragana' => 'じ', 'meaning' => 'Time'],
            ['kanji' => '分', 'hiragana' => 'ふん/ぷん', 'meaning' => 'Minute'],
            ['kanji' => '今', 'hiragana' => 'いま', 'meaning' => 'Now'],
            ['kanji' => '何', 'hiragana' => 'なに/なん', 'meaning' => 'What'],
            ['kanji' => '日', 'hiragana' => 'にち/じつ', 'meaning' => 'Day'],
            ['kanji' => '月', 'hiragana' => 'げつ/つき', 'meaning' => 'Month/Moon'],
            ['kanji' => '火', 'hiragana' => 'か', 'meaning' => 'Fire'],
            ['kanji' => '水', 'hiragana' => 'すい/みず', 'meaning' => 'Water'],
            ['kanji' => '木', 'hiragana' => 'もく/き', 'meaning' => 'Tree'],
            ['kanji' => '金', 'hiragana' => 'きん', 'meaning' => 'Gold/Metal'],
            ['kanji' => '土', 'hiragana' => 'ど/つち', 'meaning' => 'Soil'],
            ['kanji' => '本', 'hiragana' => 'ほん', 'meaning' => 'Book'],
            ['kanji' => '人', 'hiragana' => 'ひと', 'meaning' => 'Person'],
            ['kanji' => '名', 'hiragana' => 'な', 'meaning' => 'Name'],
            ['kanji' => '子', 'hiragana' => 'こ', 'meaning' => 'Child'],
            ['kanji' => '女', 'hiragana' => 'おんな/じょ', 'meaning' => 'Woman'],
            ['kanji' => '男', 'hiragana' => 'おとこ/だん', 'meaning' => 'Man'],
            ['kanji' => '学', 'hiragana' => 'がく', 'meaning' => 'Study'],
            ['kanji' => '校', 'hiragana' => 'こう', 'meaning' => 'School'],
            ['kanji' => '先', 'hiragana' => 'さき', 'meaning' => 'Previous'],
            ['kanji' => '生', 'hiragana' => 'せい/しょう', 'meaning' => 'Life'],
            ['kanji' => '先生', 'hiragana' => 'せんせい', 'meaning' => 'Teacher'],
            ['kanji' => '午', 'hiragana' => 'ご', 'meaning' => 'Noon'],
            ['kanji' => '後', 'hiragana' => 'ご', 'meaning' => 'After'],
            ['kanji' => '半', 'hiragana' => 'はん', 'meaning' => 'Half'],
            ['kanji' => '分', 'hiragana' => 'ふん/ぷん', 'meaning' => 'Minute'],
            ['kanji' => '何', 'hiragana' => 'なん/なに', 'meaning' => 'What'],
            ['kanji' => '水', 'hiragana' => 'すい/みず', 'meaning' => 'Water'],
            ['kanji' => '木', 'hiragana' => 'もく/き', 'meaning' => 'Tree'],
            ['kanji' => '金', 'hiragana' => 'きん', 'meaning' => 'Gold/Metal'],
            ['kanji' => '土', 'hiragana' => 'ど/つち', 'meaning' => 'Soil'],
            ['kanji' => '本', 'hiragana' => 'ほん', 'meaning' => 'Book'],
            ['kanji' => '人', 'hiragana' => 'ひと', 'meaning' => 'Person'],
            ['kanji' => '名', 'hiragana' => 'な', 'meaning' => 'Name'],
            ['kanji' => '子', 'hiragana' => 'こ', 'meaning' => 'Child'],
            ['kanji' => '女', 'hiragana' => 'おんな/じょ', 'meaning' => 'Woman'],
            ['kanji' => '男', 'hiragana' => 'おとこ/だん', 'meaning' => 'Man'],
            ['kanji' => '学', 'hiragana' => 'がく', 'meaning' => 'Study'],
            ['kanji' => '校', 'hiragana' => 'こう', 'meaning' => 'School'],
            ['kanji' => '先', 'hiragana' => 'さき', 'meaning' => 'Previous'],
            ['kanji' => '生', 'hiragana' => 'せい/しょう', 'meaning' => 'Life'],
            ['kanji' => '先生', 'hiragana' => 'せんせい', 'meaning' => 'Teacher'],
            ['kanji' => '午後', 'hiragana' => 'ごご', 'meaning' => 'Afternoon'],
            ['kanji' => '母', 'hiragana' => 'はは', 'meaning' => 'Mother'],
            ['kanji' => '父', 'hiragana' => 'ちち', 'meaning' => 'Father'],
            ['kanji' => '父母', 'hiragana' => 'ふぼ', 'meaning' => 'Parents'],
            ['kanji' => '友', 'hiragana' => 'とも', 'meaning' => 'Friend'],
            ['kanji' => '友達', 'hiragana' => 'ともだち', 'meaning' => 'Friend'],
            ['kanji' => '女子', 'hiragana' => 'じょし', 'meaning' => 'Girl'],
            ['kanji' => '男子', 'hiragana' => 'だんし', 'meaning' => 'Boy'],
            ['kanji' => '人々', 'hiragana' => 'ひとびと', 'meaning' => 'People'],
            ['kanji' => '山', 'hiragana' => 'やま', 'meaning' => 'Mountain'],
            ['kanji' => '川', 'hiragana' => 'かわ', 'meaning' => 'River'],
            ['kanji' => '土', 'hiragana' => 'つち', 'meaning' => 'Soil'],
            ['kanji' => '田', 'hiragana' => 'た', 'meaning' => 'Rice Field'],
            ['kanji' => '天', 'hiragana' => 'てん', 'meaning' => 'Sky'],
            ['kanji' => '天気', 'hiragana' => 'てんき', 'meaning' => 'Weather'],
            ['kanji' => '雨', 'hiragana' => 'あめ', 'meaning' => 'Rain'],
            ['kanji' => '雪', 'hiragana' => 'ゆき', 'meaning' => 'Snow'],
            ['kanji' => '書', 'hiragana' => 'か', 'meaning' => 'Write'],
            ['kanji' => '読', 'hiragana' => 'どく', 'meaning' => 'Read'],
            ['kanji' => '見', 'hiragana' => 'けん', 'meaning' => 'See'],
            ['kanji' => '聞', 'hiragana' => 'き', 'meaning' => 'Hear'],
            ['kanji' => '言', 'hiragana' => 'げん', 'meaning' => 'Say'],
            ['kanji' => '話', 'hiragana' => 'はな', 'meaning' => 'Talk'],
            ['kanji' => '食', 'hiragana' => 'しょく', 'meaning' => 'Eat'],
            ['kanji' => '飲', 'hiragana' => 'いん', 'meaning' => 'Drink'],
            ['kanji' => '行', 'hiragana' => 'い/ぎょう', 'meaning' => 'Go'],
            ['kanji' => '来', 'hiragana' => 'く', 'meaning' => 'Come'],
            ['kanji' => '出', 'hiragana' => 'しゅつ/で', 'meaning' => 'Exit'],
            ['kanji' => '入', 'hiragana' => 'い', 'meaning' => 'Enter'],
            ['kanji' => '立', 'hiragana' => 'りつ/た', 'meaning' => 'Stand'],
            ['kanji' => '座', 'hiragana' => 'ざ', 'meaning' => 'Sit'],
            ['kanji' => '休', 'hiragana' => 'きゅう/やす', 'meaning' => 'Rest'],
            ['kanji' => '見', 'hiragana' => 'み', 'meaning' => 'See'],
            ['kanji' => '聞', 'hiragana' => 'き', 'meaning' => 'Hear'],
            ['kanji' => '言', 'hiragana' => 'げん', 'meaning' => 'Say'],
            ['kanji' => '話', 'hiragana' => 'はな', 'meaning' => 'Talk'],
            ['kanji' => '読', 'hiragana' => 'どく', 'meaning' => 'Read'],
            ['kanji' => '書', 'hiragana' => 'か', 'meaning' => 'Write'],
            ['kanji' => '見る', 'hiragana' => 'みる', 'meaning' => 'Look'],
            ['kanji' => '聞く', 'hiragana' => 'きく', 'meaning' => 'Ask'],
            ['kanji' => '言う', 'hiragana' => 'いう', 'meaning' => 'Say'],
            ['kanji' => '話す', 'hiragana' => 'はなす', 'meaning' => 'Speak'],
            ['kanji' => '読む', 'hiragana' => 'よむ', 'meaning' => 'Read'],
            ['kanji' => '書く', 'hiragana' => 'かく', 'meaning' => 'Write'],
            ['kanji' => '食べる', 'hiragana' => 'たべる', 'meaning' => 'Eat'],
            ['kanji' => '飲む', 'hiragana' => 'のむ', 'meaning' => 'Drink'],
            ['kanji' => '行く', 'hiragana' => 'いく', 'meaning' => 'Go'],
            ['kanji' => '来る', 'hiragana' => 'くる', 'meaning' => 'Come'],
            ['kanji' => '出る', 'hiragana' => 'でる', 'meaning' => 'Exit'],
            ['kanji' => '入る', 'hiragana' => 'はいる', 'meaning' => 'Enter'],
            ['kanji' => '立つ', 'hiragana' => 'たつ', 'meaning' => 'Stand'],
            ['kanji' => '座る', 'hiragana' => 'すわる', 'meaning' => 'Sit'],
            ['kanji' => '休む', 'hiragana' => 'やすむ', 'meaning' => 'Rest'],
            ['kanji' => '見せる', 'hiragana' => 'みせる', 'meaning' => 'Show']
            
        ];

        foreach ($kanjiArray as $kanjiData) {
            DB::table('kanji_quiz')->insert([
                'kanji' => $kanjiData['kanji'],
                'hiragana' => $kanjiData['hiragana'],
                'meaning' => $kanjiData['meaning'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
